{
  git_branch = {
    symbol = "ğŸŒ± ";
    sformat = "[$symbol$branch(:$remote_branch)]($style) ";
    sstyle = "bold cyan";
    salways_show_remote = false;
  };

  git_status = {
    format = "([$all_status$ahead_behind]($style) )";
    style = "bold yellow";
    stashed = "ğŸ“¦ ${count}";
    ahead = "â‡¡${count}";
    behind = "â‡£${count}";
    up_to_date = ""; 
    diverged = "â‡¡${ahead_count}â‡£${behind_count}";
    conflicted = "âš ï¸ ${count}";
    deleted = "ğŸ—‘ï¸ ${count}";
    renamed = "ğŸ”€ ${count}";
    modified = "ğŸ“ ${count}";
    staged = "âœ… ${count}";
    untracked = "â“ ${count}";
  };
};
